# Generated by Django 2.2.14 on 2021-09-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210928_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='prix',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
