# Generated by Django 2.2.14 on 2021-09-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210928_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='prix',
            field=models.IntegerField(),
        ),
    ]
