# Generated by Django 2.2.14 on 2021-10-01 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210930_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='voiture',
            old_name='Description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='voiture',
            name='lieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Lieu'),
        ),
    ]
